"""
create_postgres_schema.py — Idempotent PostgreSQL schema creation script.

Uses psycopg 3 to connect to Neon PostgreSQL and safely create tables,
constraints, sequences/identities, and indexes.

Guarantees:
- Safe & Idempotent: Can be run repeatedly without destroying or recreating tables.
- No DROP or TRUNCATE statements.
- Preserves all column names, relationships, types, and constraints.
- Never logs or exposes DATABASE_URL, passwords, or credentials.
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import psycopg

ROOT_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT_DIR / ".env"

SCHEMA_SQL = """
-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    first_name TEXT,
    created_at TEXT NOT NULL
);

-- 2. Promo Codes Table
CREATE TABLE IF NOT EXISTS promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT,
    instructions TEXT,
    requirements TEXT,
    example_image TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
);

-- 3. Campaigns Table
CREATE TABLE IF NOT EXISTS campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promo_code_id BIGINT NOT NULL REFERENCES promo_codes(id),
    max_requests INTEGER NOT NULL CHECK (max_requests > 0),
    status TEXT NOT NULL DEFAULT 'closed' CHECK (status IN ('closed', 'active', 'full', 'completed')),
    created_at TEXT NOT NULL,
    closed_at TEXT
);

-- 4. Requests Table
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    site_id TEXT,
    screenshot_file_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at TEXT NOT NULL,
    reviewed_at TEXT
);

-- 5. Partial Unique Index for One Active Campaign Rule
CREATE UNIQUE INDEX IF NOT EXISTS idx_campaigns_single_active 
ON campaigns (status) 
WHERE status = 'active';

-- 6. Indexes for Users (telegram_user_id is already indexed via UNIQUE)
CREATE INDEX IF NOT EXISTS idx_users_username 
ON users (username);

-- 7. Indexes for Promo Codes (code is already indexed via UNIQUE)
CREATE INDEX IF NOT EXISTS idx_promo_codes_active 
ON promo_codes (active);

-- 8. Indexes for Campaigns
CREATE INDEX IF NOT EXISTS idx_campaigns_promo_code_id 
ON campaigns (promo_code_id);

CREATE INDEX IF NOT EXISTS idx_campaigns_status 
ON campaigns (status);

-- 9. Indexes for Requests
CREATE INDEX IF NOT EXISTS idx_requests_status 
ON requests (status);

CREATE INDEX IF NOT EXISTS idx_requests_campaign_id 
ON requests (campaign_id);

CREATE INDEX IF NOT EXISTS idx_requests_user_id 
ON requests (user_id);

CREATE INDEX IF NOT EXISTS idx_requests_user_campaign 
ON requests (user_id, campaign_id);

CREATE INDEX IF NOT EXISTS idx_requests_campaign_status 
ON requests (campaign_id, status);
"""


def create_schema():
    """Create PostgreSQL schema safely."""
    print("=== PostgreSQL Schema Creation ===")

    # Load environment
    load_dotenv(ENV_FILE, override=True)
    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        print("[-] FAIL: DATABASE_URL not set in .env", file=sys.stderr)
        return False

    print("[+] DATABASE_URL loaded safely.")

    try:
        # Connect via psycopg 3
        with psycopg.connect(database_url, connect_timeout=15) as conn:
            with conn.cursor() as cur:
                print("[+] Executing DDL statements...")
                cur.execute(SCHEMA_SQL)
            conn.commit()
            print("[+] PostgreSQL schema, constraints, and indexes created successfully!")
            return True
    except Exception as e:
        err_msg = str(e)
        if database_url in err_msg:
            err_msg = err_msg.replace(database_url, "[REDACTED_DATABASE_URL]")
        print(f"[-] FAIL during schema creation: {err_msg}", file=sys.stderr)
        return False


if __name__ == "__main__":
    success = create_schema()
    sys.exit(0 if success else 1)
